#!/usr/bin/env bash
# bash script that mixes the for loop and if sttement

for i in {1..10};
do
    if [ "$i" == 9 ]
    then
        echo -e "Best School\nHi"
    
    else
        echo "Best School"
    
    fi

done
